[package]
name = "abc244"
version = "0.1.0"
edition = "2021"

[dependencies]
superslice = "1.0.0"
itertools = "0.9.0"
itertools-num = "0.1.3"
proconio = "0.3.6"

[profile.release]
lto = true
panic = "abort"
